[project]
name = "wiatrak-wdm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gpiozero>=2.0.1",
    "picamzero>=1.0.1",
    "ultralytics>=8.3.136",
]
